### ISSUE TITLE
agentkeepalive on https?

### ISSUE THREAD

**Issue by ianshward** [mapbox/geojson-mapnikify#40]
It looks like agentkeepalive is not used on HTTPS requests - this might be a relic from the past, when there was not support for HTTPS clients in agentkeepalive.

https://github.com/mapbox/geojson-mapnikify/blob/d40a0b4844e654a623b1211da787071153952ee6/lib/get.js#L58-L59

This is just something I noticed when reviewing a recent PR, and therefore created this separate issue about it.

@DzmitryU @springmeyer

**Comment by rmrice** [comment]
Fixed in #42
